export const updateTypes = {
  AUTHUSER_CREATE: 'AUTHUSER_CREATE',
  AUTHUSER_UPDATE: 'AUTHUSER_UPDATE',
  USER_USERNAME_UPDATE: 'USER_USERNAME_UPDATE',
  USER_DISPLAYNAME_UDPATE: 'USER_DISPLAYNAME_UDPATE',
  USER_EMAIL_UPDATE: 'USER_EMAIL_UPDATE',
  USER_PUBLICINFO_USERNAME_UPDATE: 'USER_PUBLIC_INFO_USERNAME_UPDATE',
  USER_PUBLICINFO_DISPLAYNAME_UPDATE: 'USER_PUBLIC_INFO_DISPLAYNAME_UPDATE',
  USER_PUBLICINFO_EMAIL_UPDATE: 'USER_PUBLIC_INFO_EMAIL_UPDATE',
  EXCHANGE_CREATE: 'EXCHANGE_CREATE',
};

export const pathTypes = {
  ROOT: 'ROOT',
  AUTHUSERS: 'AUTHUSERS',
  AUTHUSER: 'AUTHUSER',
  USERS: 'USERS',
  USER: 'USER',
  USER_USERNAME: 'USER_USERNAME',
  USER_DISPLAYNAME: 'USER_DISPLAYNAME',
  USER_EMAIL: 'USER_EMAIL',
  USER_PUBLICINFO_USERNAME: 'USER_PUBLICINFO_USERNAME',
  USER_PUBLICINFO_DISPLAYNAME: 'USER_PUBLICINFO_DISPLAYNAME',
  USER_PUBLICINFO_EMAIL: 'USER_PUBLICINFO_EMAIL',
  EXCHANGES: 'EXCHANGES',
  EXCHANGE: 'EXCHANGE',
};

export const eventTypes = {
  CHILD_ADDED: 'CHILD_ADDED',
  CHILD_CHANGED: 'CHILD_CHANGED',
  CHILD_REMOVED: 'CHILD_REMOVED',
};
